<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/>
        PANDAS      
    </strong>
</p>

In [20]:
#Atalho para duplicar as linhas ALT+SHIFT+SETA PARA BAIXO
import pandas as pd

dados = [
    ['Ana', 'SP',1800],
    ['Joao', 'RJ',2500],
    ['Maria', 'DF',9800],
    ['Isabel', 'PB',35800],
    ['Luciano', 'MT',9800],
    ['José', 'AM',8800],
]

colunas = ['Nome','Estado', 'Salario']

#dataframe nome chique para tabela
df = pd.DataFrame(dados, columns=colunas)

df.head(2)  # 5 primeiras e 5 últimas
df.shape    # qtd de linhas e colunas (sem o parenteses)
df.info     # sempre rodar antes de comecar a analise. Retornará o tipo de dados das colunas
df.describe() # retornar calculo simples
df.dropna() # remover colunas vazias
df['Nome']

0        Ana
1       Joao
2      Maria
3     Isabel
4    Luciano
5       José
Name: Nome, dtype: str

In [19]:
df.to_excel('dados_bobos.xlsx', index=False)

In [ ]:
#buscar um codigo entre delimitadores
cod = 'codigo-1015'
p = cod.index('-') + 1
cod[p:]

In [ ]:
df['Salario'] > 2000
df [ df['Salario'] >2000] #lista os salarios maior que 2000

      Nome Estado  Salario
1     Joao     RJ     2500
2    Maria     DF     9800
3   Isabel     PB    35800
4  Luciano     MT     9800
5     José     AM     8800

In [59]:
#não precisa retornar todas as colunas, apenas a que deseja
df.groupby('Estado')['Salario'].mean().reset_index(name='MediaSalarial')

  Estado  MediaSalarial
0     AM         8800.0
1     DF         9800.0
2     MT         9800.0
3     PB        35800.0
4     RJ         2500.0
5     SP         1800.0

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/>
        EXERCÍCIO 1 — Criando uma tabela de produtos   
    </strong>
</p>

In [40]:
colunas_exercicio = ['Comprador','Produto', 'Valor','Qtd']

dados_exercicio = [
    ['Ana', 'TV',1800,2],
    ['Joao', 'Smartphone',2500,6],
    ['Maria', 'Smartphone',9800,3],
    ['Isabel', 'TV',35800,5],
    ['Luciano', 'Geladeira',9800,6],
    ['José', 'Fogão',8800,4],
]


#dataframe nome chique para tabela
df_exercicio = pd.DataFrame(dados_exercicio, columns=colunas_exercicio)

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/>
        EXERCÍCIO 2 — Visualizando as primeiras linhas
    </strong>
</p>

In [ ]:
df_exercicio.head() 
df_exercicio.tail() # 5 ultimos linhas

  Comprador     Produto  Valor  Qtd
1      Joao  Smartphone   2500    6
2     Maria  Smartphone   9800    3
3    Isabel          TV  35800    5
4   Luciano   Geladeira   9800    6
5      José       Fogão   8800    4

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/>
        EXERCÍCIO 3 — Filtrando produtos caros
    </strong>
</p>

In [ ]:
df_exercicio[ df_exercicio['Valor'] > 5000]

df_exercicio.describe()

df_exercicio['Valor'].max()

df_exercicio.groupby('Produto')['Valor'].max()

df_exercicio.groupby('Produto').agg(
    maior_preco = ('Valor', 'max'),
    maior_venda = ('Qtd','max'),
    total_venda = ('Valor','sum')
)

            maior_preco  maior_venda  total_venda
Produto
Fogão              8800            4         8800
Geladeira          9800            6         9800
Smartphone         9800            6        12300
TV                35800            5        37600

<p style="font-size: 1.1rem; color:#9beb3b; text-align: center; font-family: monospace ">
    <strong><br/><br/>
        EXERCÍCIO 4 — Resumo por categoria
    </strong>
</p>