Importar bibliotecas

In [10]:
import pandas as pd

Criando dataframe

In [11]:
#Tabela criada no python
df_entregas = pd.DataFrame({
        'id_entrega': [1,2,3], #chave primária
        'filial'    : ['FL RIO', 'FL VIX', 'FL REC'],
        'status'    : ['ENTREGUE', 'ATRASADO', 'ENTREGUE']
})

df_custos = pd.DataFrame({
        'id_custo'      : [1,2,3],
        'id_entrega'    : [1,1,3],          # chave estrangeira
        'custo'         : [114.74,89.99,35.77]
})

JOIN

In [ ]:
# inner join

pd.merge(
    df_entregas, df_custos,
    on = 'id_entrega',
    how= 'inner'    # apenas as linhas onde há informação
)

   id_entrega  filial    status  id_custo   custo
0           1  FL RIO  ENTREGUE         1  114.74
1           1  FL RIO  ENTREGUE         2   89.99
2           3  FL REC  ENTREGUE         3   35.77

In [ ]:
# full outer join

pd.merge(
    df_entregas, df_custos,
    on = 'id_entrega',
    how= 'outer'    
)

In [ ]:
# left join

pd.merge(
    df_entregas, df_custos,
    on = 'id_entrega',
    how= 'left'    
)

In [ ]:
# right join

pd.merge(
    df_entregas, df_custos,
    on = 'id_entrega',
    how= 'right'    
)

In [14]:
df_entregas_idx = df_entregas.set_index('id_entrega')
df_custos_idx = df_custos.set_index('id_entrega')

df_join = df_entregas_idx.join(df_custos_idx, how='left')
df_join.reset_index()

   id_entrega  filial    status  id_custo   custo
0           1  FL RIO  ENTREGUE       1.0  114.74
1           1  FL RIO  ENTREGUE       2.0   89.99
2           2  FL VIX  ATRASADO       NaN     NaN
3           3  FL REC  ENTREGUE       3.0   35.77